// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fksjfcxbhwkzplvdsemm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrc2pmY3hiaHdrenBsdmRzZW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTY2MDIsImV4cCI6MjA2NTg5MjYwMn0.fD07RWAKqIsRTOITD_r4V0XchX-DethiEcp_fwjgGbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);